[project]
name = "otmidterm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.2.1",
    "langchain-community>=0.3.18",
    "langchain-core>=0.3.39",
    "langchain-openai>=0.3.7",
    "langchain-qdrant>=0.2.0",
    "langgraph>=0.2.74",
    "nltk>=3.9.1",
    "qdrant-client>=1.13.2",
    "ragas>=0.2.13",
    "scikit-learn>=1.6.1",
    "unstructured>=0.14.8",
    "websockets>=15.0",
]
